from enum import StrEnum


class TradeDirection(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"


class SetupGrade(StrEnum):
    A = "A"
    B = "B"
    C = "C"


class Timeframe(StrEnum):
    M15 = "15m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"


class SignalStatus(StrEnum):
    PENDING = "PENDING"
    WATCHING = "WATCHING"
    ACTIVE = "ACTIVE"
    ENTRY_HIT = "ENTRY_HIT"
    EXPIRED = "EXPIRED"
    INVALIDATED = "INVALIDATED"
    CLOSED = "CLOSED"


class AlertType(StrEnum):
    NEW_SIGNAL = "NEW_SIGNAL"
    ENTRY_APPROACHING = "ENTRY_APPROACHING"
    ENTRY_NOW = "ENTRY_NOW"
    PAPER_OPENED = "PAPER_OPENED"
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    SIGNAL_EXPIRED = "SIGNAL_EXPIRED"
    SIGNAL_INVALIDATED = "SIGNAL_INVALIDATED"
    AUTONOMOUS_ENTRY = "AUTONOMOUS_ENTRY"
    AI_BLOCKED = "AI_BLOCKED"
    PROTECTION_FAILED = "PROTECTION_FAILED"
    POSITION_FLATTENED = "POSITION_FLATTENED"
    KILL_SWITCH = "KILL_SWITCH"
    RECONCILE_MISMATCH = "RECONCILE_MISMATCH"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    WATCHDOG_RESTART = "WATCHDOG_RESTART"
    PROCESS_RESTARTED = "PROCESS_RESTARTED"
    MANUAL_CLOSED = "MANUAL_CLOSED"


class PaperTradeStatus(StrEnum):
    PENDING = "PENDING"
    OPEN = "OPEN"
    TP1_HIT = "TP1_HIT"
    TP2_HIT = "TP2_HIT"
    STOPPED = "STOPPED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class TradingMode(StrEnum):
    PAPER = "PAPER"
    LIVE = "LIVE"
    BACKTEST = "BACKTEST"


class AuditAction(StrEnum):
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    SIGNAL_REJECTED = "SIGNAL_REJECTED"
    RISK_BLOCKED = "RISK_BLOCKED"
    PAPER_OPENED = "PAPER_OPENED"
    PAPER_CLOSED = "PAPER_CLOSED"
    LIVE_BLOCKED = "LIVE_BLOCKED"
    LIVE_ENABLED = "LIVE_ENABLED"
    ALERT_SENT = "ALERT_SENT"
    ENTRY_HIT = "ENTRY_HIT"
    ORDER_INTENT = "ORDER_INTENT"
    ORDER_SENT = "ORDER_SENT"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_FAILED = "ORDER_FAILED"
    PROTECTION_RETRY = "PROTECTION_RETRY"
    POSITION_FLATTENED = "POSITION_FLATTENED"
    RECONCILE_FIX = "RECONCILE_FIX"
    RECONCILE_ALERT = "RECONCILE_ALERT"
    KILL_SWITCH_ENGAGED = "KILL_SWITCH_ENGAGED"
    KILL_SWITCH_ARMED = "KILL_SWITCH_ARMED"
    ENTRIES_PAUSED = "ENTRIES_PAUSED"
    ENTRIES_RESUMED = "ENTRIES_RESUMED"
    CIRCUIT_OPENED = "CIRCUIT_OPENED"
    CIRCUIT_CLOSED = "CIRCUIT_CLOSED"
    WATCHDOG_RESTART = "WATCHDOG_RESTART"
    PROCESS_STARTED = "PROCESS_STARTED"
    MANUAL_CLOSE = "MANUAL_CLOSE"
